name: 'Github Script'
author: 'Funding Options'
description: 'Run simple scripts using the Github client (but with files)'
inputs:
  script-file:
    description: |
      The file to run.

      The file should be a pure javascript file, targeting node12.
      Your script should expose a function `module.exports = () => {};`

      The function can be async.

      See https://github.com/actions/github-script for more details.
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  user-agent:
    description: An optional user-agent string
    default: fundingoptions/actions/github-script
    required: false
  working-directory:
    description: The directory to run everything in
    default: '.'
    required: false
  result-encoding:
    description: The encoding to use for the result (string or json)
    default: string
    required: false
  inputs:
    description: 'JSON encoded object to pass to the script'
    default: '{}'
    required: false

outputs:
  result:
    description: The return of script-file.
    value: '${{ steps.script.outputs.result }}'

runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      id: script
      env:
        ARBITRARY_INPUTS: '${{ inputs.github-token }}'
      with:
        github-token: '${{ inputs.github-token }}'
        user-agent: '${{ inputs.user-agent }}'
        result-encoding: '${{ inputs.result-encoding }}'
        script: |
          // simulate how 'run' steps work, by moving to the expected directory.
          process.chdir('${{ inputs.working-directory }}');
          core.setFailed(`received input: ${process.env.ARBITRARY_INPUTS}`);

          return;

          const inputs = JSON.parse(process.env.ARBITRARY_INPUTS);
          const script = require('${{ inputs.script-file }}');
          const result = script({
            context, core, github, exec, glob, io, require, __original_require__, inputs
          });
          // permit async scripts to be run.
          if ('then' in result) {
            return await result;
          }
          return result;
