name: 'Github Script'
author: 'Funding Options'
description: 'Run simple scripts using the Github client (but with files)'
inputs:
  script-file:
    description: |
      The file to run.

      The file should be a pure javascript file, targeting node12.
      Your script should expose a function `module.exports = () => {};`

      The function can be async.

      See https://github.com/actions/github-script for more details.
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  user-agent:
    description: An optional user-agent string
    default: fundingoptions/actions/github-script
    required: false

runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      env:
        WORKSPACE: '${{ github.workspace }}'
      with:
        github-token: '${{ inputs.github-token }}'
        user-agent: '${{ inputs.user-agent }}'
        script: |
          const script = require('${{ inputs.script-file }}');
          const result = script({
            context, core, github, exec, glob, io, require, __original_require__
          });
          // permit async scripts to be run.
          if ('then' in result) {
            await result;
          }
