name: Github-Script

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  runs-script:
    name: Runs Script
    runs-on: ubuntu-latest
    env:
      OUTPUT_FILE: '.hello-world'
      CONTENTS: 'Hello, World!'

    steps:
      - uses: actions/checkout@v3
      - uses: ./github-script
        with:
          script-file: '.github/scripts/examples/write-content.js'

      - name: Script can use environment variables
        run: |
          contents="$(cat "${OUTPUT_FILE}")"
          if [ "${contents}" != "${CONTENTS}" ]; then
            echo "Expected contents to be '${CONTENTS}', but got '${contents}'"
            exit 1
          fi

      - uses: ./github-script
        id: get-run-id
        with:
          script-file: '.github/scripts/examples/get-run-id.js'

      - name: Script can use the context
        run: |
          run_id='${{ steps.get-run-id.outputs.result }}'
          if [ "${run_id}" != '${{ github.run_id }}' ]; then
            echo "Expected run_id to be '${{ github.run_id }}', but got '${run_id}'"
            exit 1
          fi

  supports-working-directory:
    name: Supports Working Directory
    runs-on: ubuntu-latest
    env:
      _working_directory: './examples'
    defaults:
      run:
        working-directory: '${{ env._working_directory }}'

    steps:
      - uses: actions/checkout@v3
      - uses: ./github-script
        id: get-cwd
        with:
          # script-file is relative to the working-directory
          script-file: '../.github/scripts/examples/get-cwd.js'
          working-directory: '${{ env._working_directory }}'

      - name: Script is run in the specified 'working-directory'
        shell: python
        run: |
          import os
          detected_cwd = '${{ steps.get-cwd.outputs.result }}'
          assert detected_cwd == os.getcwd(), (
            f"Expected detected_cwd to be '{os.getcwd()}', "
            f"but got '{detected_cwd}'"
          )
